kilometer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import RedirectView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),

    # store api urls
    url(r'^api/store/', include(('store.api.urls', 'api-store'), namespace='api-store')),

    # website urls
    url(r'^', include('store.urls')),

    # manager panel urls
    url(r'^management-panel/', include('manager_panel.urls')),

    # user panel urls
    url(r'^profile/', include('user_panel.urls')),

    # user panel api urls
    url(r'^api/user/', include('user_panel.api.urls')),

    # user manager api urls
    url(r'^api/manager/', include('manager_panel.api.urls')),

    url(r'^api-auth/', include('rest_framework.urls')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls import url, re_path
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.generic.base import RedirectView


app_name = 'store'

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^error-404/$', views.error_404, name='error404'),
    re_path(r'product/(?P<pk>\w+)', views.single_product, name='singleProduct'),
    path('global-search/products/', views.global_search, name='globalSearch'),
    path('sub-category/<int:pk>/', views.sub_category_products, name='subCategory'),
    path('category/<str:slug>/', views.category_products, name='Category'),
    path('cart/', views.cart, name='cart'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('scrape-products/', views.scrape_products, name='scrape-product'),
    # re_path(
    #     r'product/(?P<pk>\w+)/(?P<slug>[-\w]+)/',
    #     TemplateView.as_view(template_name="store/single-product.html"),
    #     name='singleProduct'),
]

user_panel/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers
from store.models import User

from . import views

app_name = 'api-user'

router = routers.DefaultRouter()
router.register('returned-ware', views.ReturnedWareViewSet)
router.register('address', views.UserAddressViewSet)
router.register('favorite-ware', views.FavoriteWareViewSet)
router.register('resend-code', views.ResendCodeViewSet)

urlpatterns = [
    path('info/', views.UserInfoView.as_view(), name='user_create'),
    # path('login/', views.LoginAPIView.as_view(), name='user_login'),
    path('signup/', views.SignUpAPIView.as_view(), name='user_signup'),
    path('verify-user/', views.UserPhoneRegisterAPIView.as_view(), name='verifyUser'),
    # path('address/', views.UserAddressAPIView.as_view(), name='address'),
    # path('address/<int:pk>/', views.UpdateUserAddressView.as_view(), name='update-address'),
    path('isAdmin/', views.IsManagerAPIView.as_view(), name='isAdmin'),
    path('sales/', views.SaleListAPIView.as_view(), name='sales-lists'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('', include(router.urls)),
]

user_panel/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

app_name = 'user_panel'

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^login/$', views.login, name='login'),
    url(r'^profile-favorites/$', views.profile_favorites, name='profileFavorites'),
    url(r'^profile-orders/$', views.profile_orders, name='profileOrders'),
    url(r'^profile-personal-info/$', views.profile_personal_info, name='profilePersonalInfo'),
    url(r'^profile-additional-info/$', views.profile_additional_info, name='profileAdditionalInfo'),
    url(r'^profile-my-addresses/$', views.profile_my_addresses, name='profileMyAddresses'),
    url(r'^profile-orders-return/$', views.profile_orders_return, name='profileOrdersReturn'),
    url(r'^password-change/$', views.password_change, name='passwordChange'),
    url(r'^forgot-password/$', views.forgot_password, name='forgotPassword'),
    url(r'^verify-phone-number/$', views.verify_phone_number, name='verifyPhoneNumber'),


    url(r'^cart/$', views.cart, name='cart'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

user_panel/api/views.py
from random import randint

from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from kavenegar import KavenegarAPI, APIException, HTTPException
from rest_framework import status, viewsets, mixins
from rest_framework.generics import (
    DestroyAPIView,
    ListAPIView,
    ListCreateAPIView,
    RetrieveUpdateAPIView,
    UpdateAPIView)
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.authentication import JWTAuthentication

from kilometer.settings import KAVENEGAR_APIKEY
from store.models import User, UserAddress, Sale, ReturnedWare, FavoriteWare
from . import serializers
from .permissions import IsOwner, IsTimeValid, IsProductInSale, IsProductReturnedBefore


class UserInfoView(RetrieveUpdateAPIView):
    """Show detailed of user"""
    serializer_class = serializers.UserUpdateSerializer
    authentication_classes = (JWTAuthentication,)

    def get_object(self):
        """Retrieve and return authenticated user"""
        return self.request.user


# class UserAPIView(APIView):
#     serializer_class = serializers.UserUpdateSerializer
#
#     def get(self, request):
#         user = User.objects.get(id=request.user.id)
#         users = User.objects.all()
#         if user.groups.filter(name="Manager").exists():
#             serializer = serializers.UserUpdateSerializer(users, many=True)
#             return Response(serializer.data)
#         else:
#             serializer = serializers.UserUpdateSerializer(user)
#             return Response(serializer.data)
#
#     def post(self, request):
#         serializer = serializers.UserUpdateSerializer(data=request.data)
#
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#
#         else:
#             return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#
#     def put(self, request):
#         user = User.objects.get(id=request.user.id)
#         serializer = serializers.UserUpdateSerializer(user, data=request.data)
#
#         if serializer.is_valid():
#             serializer.save()
#             return Response({"message": "User updated successfully"})
#         else:
#             return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserAddressViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.AddressSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = UserAddress.objects.all()

    def get_queryset(self):
        queryset = UserAddress.objects.filter(user=self.request.user)
        return queryset

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


# class UserAddressAPIView(ListCreateAPIView):
#     serializer_class = serializers.AddressSerializer
#     authentication_classes = (JWTAuthentication,)
#     permission_classes = (IsAuthenticated,)
#
#     def get(self, request):
#         user_address = UserAddress.objects.filter(user=request.user)
#         serializer = serializers.AddressSerializer(user_address, many=True)
#         if len(serializer.data) == 0:
#             return Response(
#                 {
#                     'error': 'شما آدرسی ندارید'
#                 },
#                 status=status.HTTP_400_BAD_REQUEST
#             )
#         return Response(serializer.data)
#
#     def post(self, request):
#         user = get_object_or_404(get_user_model(), phone_number=request.user.phone_number)
#         serializer = serializers.AddressSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save(user=user)
#             return Response({"message": "Address added successfully"})
#
#     def put(self, request):
#         serializer = serializers.AddressSerializer(data=request.data)
#         if serializer.is_valid():
#             # address = UserAddress.objects.get(id=serializer.data['id'])
#             return Response(serializer.data)
#         else:
#             return Response(serializer.errors)
#
#
# class UpdateUserAddressView(RetrieveUpdateAPIView):
#     authentication_classes = (JWTAuthentication,)
#     permission_classes = (IsOwner,)
#     serializer_class = serializers.AddressSerializer
#     queryset = UserAddress.objects.all()


class SignUpAPIView(APIView):
    serializer_class = serializers.UserSignUpSerializer

    def post(self, request):
        serializer = serializers.UserSignUpSerializer(data=request.data)
        if serializer.is_valid():
            serializer.validated_data['generated_token'] = randint(100000, 999999)
            try:
                api = KavenegarAPI(KAVENEGAR_APIKEY)
                params = {'sender': '1000596446', 'receptor': serializer.validated_data['phone_number'],
                          'message': 'کالا نگار\n' + 'کد تایید:' + str(serializer.validated_data['generated_token'])}
                response = api.sms_send(params)
                serializer.save()
                return Response({"user": "signed up successfully",
                                 "generated token": serializer.data['generated_token']})

            except APIException:
                return Response(
                    {
                        'error': 'ارسال کد تایید با مشکل مواجه شده است',
                        'type': 'APIException'
                    },
                    status=status.HTTP_400_BAD_REQUEST
                )
            except HTTPException:
                return Response(
                    {
                        'error': 'ارسال کد تایید با مشکل مواجه شده است',
                        'type': 'HTTPException'
                    },
                    status=status.HTTP_400_BAD_REQUEST
                )

        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserPhoneRegisterAPIView(APIView):

    def put(self, request):
        data = request.data
        user = get_object_or_404(get_user_model(), phone_number=data['phone_number'])
        if user:
            serializer = serializers.UserPhoneRegisterSerializer(user, data=data)
            if serializer.is_valid():
                if serializer.data['generated_token'] == int(data.get("generated_token")):
                    user.is_verified = True
                    user.save()
                    return Response({"user": "verified successfully"})
                else:
                    return Response(
                        {'error': 'The entered token is invalid'},
                        status=status.HTTP_400_BAD_REQUEST
                    )
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# class FavoriteWareListAPIView(ListAPIView):
#     authentication_classes = (JWTAuthentication,)
#     permission_classes = (IsOwner,)
#     serializer_class = serializers.FavoriteWareSerializer
#
#     def get_queryset(self):
#         queryset = FavoriteWare.objects.filter(user=self.request.user)
#         return queryset
#
#
# class FavoriteWareDestroyAPIView(DestroyAPIView):
#     authentication_classes = (JWTAuthentication,)
#     permission_classes = (IsOwner,)
#     serializer_class = serializers.FavoriteWareSerializer
#     queryset = FavoriteWare.objects.all()


class SaleListAPIView(ListAPIView):
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsOwner,)
    serializer_class = serializers.SaleSerializer

    def get_queryset(self):
        queryset = Sale.objects.filter(user=self.request.user, status__in=['processing', 'posted', 'delivered'])
        return queryset


# class LoginAPIView(APIView):
#
#     serializer_class = serializers.UserLoginSerializer
#
#     def post(self, request):
#         serializer = serializers.UserLoginSerializer(data=request.data)
#         if serializer.is_valid():
#             user = serializer.validated_data["user"]
#             login(request, user)
#             return Response({"user": "logged in"})
#         else:
#             return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def is_manager(user):
    return user.groups.filter(name='Manager').exists()


class IsManagerAPIView(APIView):

    def get(self, request):
        user = User.objects.get(phone_number=request.user.phone_number)
        if is_manager(user):
            return Response(
                {
                    'isManager': True,
                },
                status=status.HTTP_200_OK
            )
        else:
            return Response(
                {
                    'isManager': False,
                },
                status=status.HTTP_200_OK
            )


class ReturnedWareViewSet(viewsets.GenericViewSet,
                          mixins.ListModelMixin,
                          mixins.RetrieveModelMixin,
                          mixins.CreateModelMixin,
                          mixins.DestroyModelMixin):
    """All method except update"""

    serializer_class = serializers.ReturnedWareSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsTimeValid, IsProductInSale, IsProductReturnedBefore)
    queryset = ReturnedWare.objects.all()


class ChangePasswordView(UpdateAPIView):
    """
    An endpoint for changing password.
    """
    serializer_class = serializers.ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):

user_panel/views.py
from django.shortcuts import render


def profile(request):
    return render(request, 'user_panel/profile.html')


def profile_favorites(request):
    return render(request, 'user_panel/profile-favorites.html')


def profile_personal_info(request):
    return render(request, 'user_panel/profile-personal-info.html')


def profile_orders(request):
    return render(request, 'user_panel/profile-orders.html')


def profile_additional_info(request):
    return render(request, 'user_panel/profile-additional-info.html')


def profile_orders_return(request):
    return render(request, 'user_panel/profile-orders-return.html')


def password_change(request):
    return render(request, 'user_panel/password-change.html')


def verify_phone_number(request):
    return render(request, 'user_panel/verify-phone-number.html')


def cart(request):
    return render(request, 'user_panel/cart.html')


def checkout(request):
    return render(request, 'user_panel/checkout.html')


def login(request):
    return render(request, 'user_panel/login.html')


def signup(request):
    return render(request, 'user_panel/signup.html')


def welcome(request):
    return render(request, 'user_panel/welcome.html')


def forgot_password(request):
    return render(request, 'user_panel/forgot-password.html')


def profile_my_addresses(request):
    return render(request, 'user_panel/my-addresses.html')

user_panel/templates/user_panel/_user-panel-sidebar.html
{% load static %}
<div class="profile-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-1">
    <div class="profile-box">
        <div class="profile-box-header">
            <div class="profile-box-avatar">
                <img src="{% static 'store/asset/image/homePage/svg/user.svg' %}" alt="">
            </div>
            <button data-toggle="modal" data-target="#myModal" class="profile-box-btn-edit">
                <i class="fa fa-pencil"></i>
            </button>
            <!-- Modal Core -->
            <div class="modal-share modal-width-custom modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">تغییر نمایه کاربری شما</h4>
                        </div>
                        <div class="modal-body">
                            <ul class="profile-avatars default text-center">
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/user.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-1.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-2.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-3.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-4.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-5.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-6.svg' %}">
                                </li>
                                <li>
                                    <img class="profile-avatars-item" src="{% static 'store/asset/image/homePage/svg/avatar-7.svg' %}">
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal Core -->
        </div>
        <div class="profile-box-username" id="user-name"></div>
        <div class="profile-box-tabs">
            <a href="{% url 'user_panel:passwordChange' %}" class="profile-box-tab profile-box-tab-access">
                <i class="now-ui-icons ui-1_lock-circle-open"></i>
                تغییر رمز
            </a>
            <a onclick="logout()" href="/" class="profile-box-tab profile-box-tab--sign-out">
                <i class="now-ui-icons media-1_button-power"></i>
                خروج از حساب
            </a>
        </div>
    </div>
    <div class="responsive-profile-menu show-md">
        <div class="btn-group">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-navicon"></i>
                حساب کاربری شما
            </button>
            <div class="dropdown-menu dropdown-menu-right text-right">
                <a href="{% url 'user_panel:profile' %}" class="dropdown-item" id="sidebar-mobile-profile">
                    <i class="now-ui-icons users_single-02"></i>
                    پروفایل
                </a>
                <a href="{% url 'user_panel:profileOrders' %}" class="dropdown-item" id="sidebar-mobile-orders">
                    <i class="now-ui-icons shopping_basket"></i>
                    همه سفارش ها
                </a>
                <a href="{% url 'user_panel:profileOrdersReturn' %}" class="dropdown-item" id="sidebar-mobile-return-orders">
                    <i class="now-ui-icons files_single-copy-04"></i>
                    درخواست مرجوعی
                </a>
                <a href="{% url 'user_panel:profileFavorites' %}" class="dropdown-item" id="sidebar-mobile-favorites">
                    <i class="now-ui-icons ui-2_favourite-28"></i>
                    لیست علاقمندی ها
                </a>
                <a href="{% url 'user_panel:profilePersonalInfo' %}" class="dropdown-item" id="sidebar-mobile-personal-info">
                    <i class="now-ui-icons business_badge"></i>
                    اطلاعات شخصی
                </a>
                <a href="{% url 'user_panel:profileMyAddresses' %}" class="dropdown-item" id="sidebar-mobile-my-addresses">
                    <i class="now-ui-icons business_badge"></i>
                    آدرس های من
                </a>
            </div>
        </div>
    </div>
    <div class="profile-menu hidden-md">
        <div class="profile-menu-header">حساب کاربری شما</div>
        <ul class="profile-menu-items">
            <li>
                <a href="{% url 'user_panel:profile' %}" id="sidebar-profile">
                    <i class="now-ui-icons users_single-02"></i>
                    پروفایل
                </a>
            </li>
            <li>
                <a href="{% url 'user_panel:profileOrders' %}" id="sidebar-orders">
                    <i class="now-ui-icons shopping_basket"></i>
                    همه سفارش ها
                </a>
            </li>
            <li>
                <a href="{% url 'user_panel:profileOrdersReturn' %}" id="sidebar-return-orders">
                    <i class="now-ui-icons files_single-copy-04"></i>
                    درخواست مرجوعی
                </a>
            </li>
            <li>
                <a href="{% url 'user_panel:profileFavorites' %}" id="sidebar-favorites">
                    <i class="now-ui-icons ui-2_favourite-28"></i>
                    لیست علاقمندی ها
                </a>
            </li>
            <li class="w-100">
                <a href="{% url 'user_panel:profilePersonalInfo' %}"  id="sidebar-personal-info">
                    <i class="now-ui-icons business_badge"></i>
                    اطلاعات شخصی
                </a>
            </li>
            <li>
                <a href="{% url 'user_panel:profileMyAddresses' %}" id="sidebar-my-addresses">
                    <i class="now-ui-icons location_pin"></i>
                    آدرس های من
                </a>
            </li>
        </ul>
    </div>
</div>

{% block js %}
    <script src="{% static 'store/vendor/js/core/jquery.3.2.1.min.js' %}"></script>
    <script src="{% static 'store/vendor/js/core/axios.min.js' %}"></script>
    <script>
        let config = {
        headers: {
            Authorization: `Bearer ${localStorage.getItem('accessToken')}`
        },
    }
    axios.get('/api/user/info', config)
        .then(response => {
            let userInfo = response.data;
            $("#user-name").text(userInfo['name'])
        })
        .catch(error => {
            console.log(error.response)
        })
    </script>

    <script>
        const logout = () => {
            localStorage.setItem('accessToken' , '')
        }
    </script>
    <script>
        let pageURL = window.location.href.split('/')
        switch (pageURL[pageURL.length - 2]) {
            case 'profile':
                $("#sidebar-profile").addClass('active')
                $("#sidebar-mobile-profile").addClass('active-menu')
                break
            case 'profile-orders':
                $("#sidebar-orders").addClass('active')
                $("#sidebar-mobile-orders").addClass('active-menu')
                break
            case 'profile-orders-return':
                $("#sidebar-return-orders").addClass('active')
                $("#sidebar-mobile-return-orders").addClass('active-menu')
                break
            case 'profile-favorites':
                $("#sidebar-favorites").addClass('active')
                $("#sidebar-mobile-favorites").addClass('active-menu')
                break
            case 'profile-personal-info':
                $("#sidebar-personal-info").addClass('active')
                $("#sidebar-mobile-personal-info").addClass('active-menu')
                break
            case 'profile-my-addresses':
                $("#sidebar-my-addresses").addClass('active')
                $("#sidebar-mobile-my-addresses").addClass('active-menu')
                break
        }
    </script>

{% endblock %}

user_panel/templates/user_panel/verify-phone-number.html
{% extends 'store/_mini-base.html' %}
{% load static %}
{% block title %}
    <title>ایجاد حساب کاربری</title>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="main-content col-12 col-md-7 col-lg-5 mx-auto">
                <div class="account-box verify-phone-number">
                    <div class="logo-in-box text-center pt-3 pb-2">
                        <a href="#" class="d-block">
                            <img src="{% static 'store/asset/image/homePage/logo.png' %}" alt="">
                        </a>
                    </div>
                    <div class="message-light">
                        برای شماره همراه<span id="user-phone" style="font-weight: bold"></span> کد تایید ارسال گردید
                        <a href="{% url 'api-user:user_signup' %}" class="btn-link-border form-account-link">
                            ویرایش شماره
                        </a>
                    </div>
                    <div class="account-box-content">
                        <form class="form-account">
                            <div class="form-account-title">کد تایید را وارد کنید</div>
                            <div class="form-account-row numbers-verify">
                                <div class="lines-number-input" onkeyup="getNumVal()">
                                    <input type="text" class="line-number" maxlength="1" id="number-1">
                                    <input type="text" class="line-number" maxlength="1" id="number-2">
                                    <input type="text" class="line-number" maxlength="1" id="number-3">
                                    <input type="text" class="line-number" maxlength="1" id="number-4">
                                    <input type="text" class="line-number" maxlength="1" id="number-5">
                                    <input type="text" class="line-number" maxlength="1" id="number-6">
                                </div>
                            </div>
                            <div class="form-account-row">
                                دریافت مجدد کد تایید(
                                <p id="countdown-verify-end"></p>)
                            </div>
                        </form>
                    </div>
                    <div class="account-box-footer">
                        <span>کاربر جدید هستید؟</span>
                        <a href="{% url 'user_panel:signup' %}" class="btn-link-border">ثبت‌نام در
                            کالانگار</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <input type="hidden" url="{% url 'user_panel:welcome' %}" id="url-welcome">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/signup.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/verify-phone-number.js' %}"></script>
{% endblock %}

user_panel/templates/user_panel/welcome.html
{% extends 'store/_mini-base.html' %}
{% load static %}

{% block title %}
    <title>به کالانگار خوش آمدید</title>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="main-content col-12 col-md-7 col-lg-5 mx-auto">
                <div class="account-box text-center">
                    <a href="#" class="logo">
                        <img src="{% static 'store/asset/image/homePage/logo.png' %}" alt="">
                    </a>
                    <div class="account-box-title text-center">به کالانگار خوش آمدید</div>
                    <div class="account-box-content">
                        <div class="account-box-message">
                            <i class="account-box-message-icon now-ui-icons users_single-02"></i>
                            <h3>حساب کاربری شما در کالانگار ساخته شد</h3>
                            <p>اکنون می‌توانید به صفحه‌ای که در آن بودید بازگردید و یا با تکمیل اطلاعات حساب کاربری
                                خود به کلیه امکانات و
                                سرویس‌های کالانگار و سرویس‌های وابسته به آن دسترسی داشته باشید</p>
                            <ul class="account-box-message-links">
                                <li>
                                    <div class="parent-btn">
                                        <a href="{% url 'user_panel:profileAdditionalInfo' %}" class="dk-btn dk-btn-info">
                                            تکمیل حساب کاربری
                                            <i class="now-ui-icons users_single-02"></i>
                                        </a>
                                    </div>
                                </li>
                                <li><a href="#" class="btn-link-border">بازگشت به صفحه‌ای که در آن بودید</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>

    </script>
{% endblock %}