kilometer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import RedirectView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),

    # store api urls
    url(r'^api/store/', include(('store.api.urls', 'api-store'), namespace='api-store')),

    # website urls
    url(r'^', include('store.urls')),

    # manager panel urls
    url(r'^management-panel/', include('manager_panel.urls')),

    # user panel urls
    url(r'^profile/', include('user_panel.urls')),

    # user panel api urls
    url(r'^api/user/', include('user_panel.api.urls')),

    # user manager api urls
    url(r'^api/manager/', include('manager_panel.api.urls')),

    url(r'^api-auth/', include('rest_framework.urls')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = 'api-store'

router = routers.DefaultRouter()
router.register('category', views.CategoryViewSet)
router.register('cart', views.UserCartViewSet)
router.register('sale', views.SaleViewSet)
# router.register('comment', views.WareCommentViewSet)
# router.register(r'address', views.UserAddressViewSet)


urlpatterns = [
    path('category/<str:slug>/', views.category_list, name='categoryList'),
    path('category/<str:slug>/ware/', views.ware_list, name='wareList'),
    path(
        'ware/<str:pk>/',
        views.WareRetrieveApiView.as_view(),
        name='ware-retrieve'
        ),
    path(
        'comment/',
        views.WareCommentListCreateAPIView.as_view(),
        name='ware-comment'
    ),
    path(
        'instant-offer/',
        views.InstantOfferListApiView.as_view(),
        name='instant-offer'
    ),
    path(
        'slide-show/',
        views.SlideShowImageListApiView.as_view(),
        name='slide-show'
    ),
    path(
        'sub-category/<int:pk>/ware/',
        views.WareRetrieveBySubCategoryApiView.as_view(),
        name='ware-retrieve-by-sub-category'
    ),
    path(
        'sub-sub-category/<int:pk>/ware/',
        views.WareRetrieveBySubSubCategoryApiView.as_view(),
        name='ware-retrieve-by-sub-sub-category'
    ),
    path(
        'tag/<str:slug>/ware/',
        views.WareRetrieveByTagApiView.as_view(),
        name='ware-retrieve-by-sub-sub-category'
    ),
    path(
        'sub-category/<int:pk>/',
        views.SubCategoryRetrieveApiView.as_view(),
        name='sub-category-retrieve'
    ),
    path(
        'sub-sub-category/<int:pk>/',
        views.SubSubCategoryRetrieveApiView.as_view(),
        name='sub-sub-category-retrieve'
    ),
    path(
        'sub-sub-category/<int:pk>/brand',
        views.SubSubCategoryBrandsRetrieveAPIView.as_view(),
        name='sub-sub-category-brand-retrieve'
    ),
    path(
        'ware/top-ware/',
        views.TopSevenWareListApiView.as_view(),
        name='top-five-ware-list'
    ),
    path(
        'forget-password/',
        views.ForgetPasswordAPIView.as_view(),
        name='forget-password'
    ),
    path(
        'report/',
        views.ReportAPIView.as_view(),
        name='report'
    ),
    path(
        'delete-cart/',
        views.DeleteCart.as_view(),
        name='DeleteCart'
    ),
    path(
        'global-search/',
        views.WareGlobalSearch.as_view(),
        name='global-search'
    ),
    path('', include(router.urls)),
]

store/urls.py
from django.conf.urls import url, re_path
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.generic.base import RedirectView


app_name = 'store'

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^error-404/$', views.error_404, name='error404'),
    re_path(r'product/(?P<pk>\w+)', views.single_product, name='singleProduct'),
    path('global-search/products/', views.global_search, name='globalSearch'),
    path('sub-category/<int:pk>/', views.sub_category_products, name='subCategory'),
    path('category/<str:slug>/', views.category_products, name='Category'),
    path('cart/', views.cart, name='cart'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('scrape-products/', views.scrape_products, name='scrape-product'),
    # re_path(
    #     r'product/(?P<pk>\w+)/(?P<slug>[-\w]+)/',
    #     TemplateView.as_view(template_name="store/single-product.html"),
    #     name='singleProduct'),
]

store/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
import kavenegar
from kilometer.settings import KAVENEGAR_APIKEY

UserModel = get_user_model()


class PasswordResetForm(forms.Form):
    phone_number = forms.CharField(label='شماره موبایل', max_length=11,
                                   validators=[RegexValidator(regex=r'09(\d{9})$')])

    def send_sms(self, phone_number, reset_link):
        try:
            api = kavenegar.KavenegarAPI(KAVENEGAR_APIKEY)
            message = f'برای بازیابی رمز عبور روی لینک زیر کلیک کنید \n {reset_link}'
            params = {
                'sender': '1000596446',
                'receptor': phone_number,
                'message': message,
            }
            response = api.sms_send(params)
            print(response)
        except kavenegar.APIException as e:
            print(e)
        except kavenegar.HTTPException as e:
            print(e)

    def get_users(self, phone_number):
        return UserModel.objects.get(phone_number=phone_number)

    def save(self, domain_override=None,
             use_https=False, token_generator=default_token_generator,
             request=None):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        phone_number = self.cleaned_data["phone_number"]
        if not domain_override:
            current_site = get_current_site(request)
            site_name = current_site.name
            domain = current_site.domain
        else:
            site_name = domain = domain_override
        user = self.get_users(phone_number)
        user_phone_number = user.phone_number
        protocol = 'https' if use_https else 'http'
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = token_generator.make_token(user)
        reset_link = protocol + '://' + domain + reverse('password_reset_confirm',
                                                         args=[uid, token])
        print(reset_link)
        self.send_sms(user_phone_number, reset_link)

store/api/views.py
import datetime
import math
import operator
from random import randint

from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.db.models import Case, When
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters, status
from rest_framework import generics
from rest_framework import viewsets, mixins
from rest_framework.decorators import action
from rest_framework.exceptions import NotFound
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.decorators import api_view
import secrets
import string
from store import models
from . import serializers
from . import permissions
from kavenegar import KavenegarAPI, APIException, HTTPException
from kavenegar import json
from kilometer.settings import KAVENEGAR_APIKEY
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from .permissions import IsOwnerOrReadOnly

# import secrets


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 20
    page_size_query_param = 'page_size'
    max_page_size = 100


@api_view(['GET'])
def category_list(request, slug):
    """
        List and retrieve category, subcategory, subsubcategory
    """
    print(slug)

    # category
    try:
        obj = models.Category.objects.get(slug=slug)
        print('cat')
        obj_json = serializers.CategoryListSerializer(obj).data
        message = {
            'type': 'category',
            'data': obj_json
        }
        return Response(
            message,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass

    # sub category
    try:
        obj = models.SubCategory.objects.get(slug=slug)
        print('sub-cat')
        obj_json = serializers.SubCategorySerializer(obj).data
        message = {
            'type': 'sub-category',
            'data': obj_json
        }
        return Response(
            message,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass

    # sub sub category
    try:
        obj = models.SubSubCategory.objects.get(slug=slug)
        print('subsubcat')
        obj_json = serializers.SubSubCategorySerializer(obj).data
        message = {
            'type': 'sub-sub-category',
            'data': obj_json
        }
        return Response(
            message,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass
    
    return Response(
        {
            'error': 'دسته بندی وجود ندارد!'
        },
        status=status.HTTP_404_NOT_FOUND
    )


@api_view(['GET'])
def ware_list(request, slug):
    """
        List ware for category, subcategory, subsubcategory
    """
    print(slug)

    # category
    try:
        category = models.Category.objects.get(slug=slug)
        ware_obj = models.Ware.objects.filter(sub_sub_category__sub_category__category=category)
        obj_json = serializers.BaseWareSerializer(ware_obj, many=True).data
        return Response(
            obj_json,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass

    # sub category
    try:
        sub_category = models.SubCategory.objects.get(slug=slug)
        ware_obj = models.Ware.objects.filter(sub_sub_category__sub_category=sub_category)
        obj_json = serializers.BaseWareSerializer(ware_obj, many=True).data
        return Response(
            obj_json,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass

    # sub sub category
    try:
        sub_sub_category = models.SubSubCategory.objects.get(slug=slug)
        ware_obj = models.Ware.objects.filter(sub_sub_category=sub_sub_category)
        obj_json = serializers.BaseWareSerializer(ware_obj, many=True).data
        return Response(
            obj_json,
            status=status.HTTP_200_OK
        )
    except ObjectDoesNotExist:
        pass
    
    return Response(
        {
            'error': 'دسته بندی وجود ندارد!'
        },
        status=status.HTTP_404_NOT_FOUND
    )


class SlideShowImageListApiView(generics.ListAPIView):
    """List slideshow images"""

    serializer_class = serializers.SlideShowSerializer
    authentication_classes = (JWTAuthentication,)
    queryset = models.SlideShow.objects.filter(is_shown=True)


class CategoryViewSet(viewsets.GenericViewSet,
                      mixins.ListModelMixin):
    """List category"""

    authentication_classes = (JWTAuthentication,)
    serializer_class = serializers.CategoryListSerializer
    pagination_class = StandardResultsSetPagination
    queryset = models.Category.objects.all()

    # def get_serializer_class(self):
    #     if self.action == 'list':
    #         return serializers.CategoryListSerializer
    #     else:
    #         return serializers.CategoryRetrieveSerializer


# class SpecialOfferView(generics.ListAPIView):
#     """List special offer"""
#
#     serializer_class = serializers.SpecialOfferSerializer
#     authentication_classes = (JWTAuthentication,)
#     pagination_class = StandardResultsSetPagination
#     queryset = models.SpecialOffer.objects.all()
#
#
# class TopFiveSpecialOfferView(generics.ListAPIView):
#     """List top 5 special offer"""
#     serializer_class = serializers.SpecialOfferSerializer
#     authentication_classes = (JWTAuthentication,)
#     queryset = models.SpecialOffer.objects.all().order_by('-off')[:5]

class InstantOfferListApiView(generics.ListAPIView):
    """List instant offers wares"""

    serializer_class = serializers.InstantOfferSerializer
    authentication_classes = (JWTAuthentication,)
    queryset = models.InstantOffer.objects.filter(deadline__gte=datetime.datetime.now())


class TopSevenWareListApiView(generics.ListAPIView):
    """List top 7 ware by view"""

    serializer_class = serializers.SubSubCategoryMainPageSerializer
    authentication_classes = (JWTAuthentication,)
    queryset = models.SubSubCategory.objects.all()

    # def get_queryset(self):
    #     """Return objects"""
    #     sub_category_id = self.request.query_params.get('sub-category')
    #     queryset = self.queryset
    #     if sub_category_id:
    #         queryset = queryset.filter(sub_category_id=sub_category_id)
    #
    #     # return queryset.order_by('-view')[:5]
    #     return queryset


class WareGlobalSearch(generics.ListAPIView):
    """List ware by global search"""
    serializer_class = serializers.BaseWareSerializer
    authentication_classes = (JWTAuthentication,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Ware.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.OrderingFilter,
        filters.SearchFilter
    ]
    ordering_fields = ['rate', 'specialoffer__off', 'created_on']

    def get_queryset(self):
        """Return objects"""
        queryset = self.queryset.all()
        # get query params
        search = self.request.query_params.get('search')
        brand = self.request.query_params.get('brand')
        ordering = self.request.query_params.get('ordering')
        if search:
            queryset = queryset.filter(
                Q(sub_sub_category__name__icontains=search) |
                Q(brand__fa_name__icontains=search) |
                Q(brand__en_name__icontains=search) |
                Q(id__icontains=search) |
                Q(name__icontains=search) |
                Q(en_name__icontains=search) |
                Q(sub_sub_category__sub_category__name__icontains=search) |
                Q(sub_sub_category__sub_category__category__name__icontains=search)
            )

        # filter by brand
        if brand:
            brand = brand.split(',')
            queryset = queryset.filter(brand_id__in=brand)

        pk_list = []
        # ordering by view, price and sale count
        if ordering:
            if ordering == 'view':
                temp = sorted(queryset, key=operator.attrgetter('view'), reverse=False)
                for t in temp:
                    pk_list.append(t.id)
            elif ordering == '-view':
                temp = sorted(queryset, key=operator.attrgetter('view'), reverse=True)
                for t in temp:
                    pk_list.append(t.id)
            if ordering == 'sale_count':
                temp = sorted(queryset, key=operator.attrgetter('sale_count'), reverse=False)
                for t in temp:
                    pk_list.append(t.id)
            elif ordering == '-sale_count':
                temp = sorted(queryset, key=operator.attrgetter('sale_count'), reverse=True)
                for t in temp:
                    pk_list.append(t.id)
            if ordering == 'price':
                temp = sorted(queryset, key=operator.attrgetter('price'), reverse=False)
                for t in temp:
                    pk_list.append(t.id)
            elif ordering == '-price':
                temp = sorted(queryset, key=operator.attrgetter('price'), reverse=True)
                for t in temp:
                    pk_list.append(t.id)

        if len(pk_list) > 0:
            preserved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(pk_list)])
            queryset = models.Ware.objects.filter(pk__in=pk_list).order_by(preserved)

        return queryset


class WareRetrieveBySubSubCategoryApiView(generics.ListAPIView):
    """Retrieve sub sub category with all ware"""

    serializer_class = serializers.BaseWareSerializer
    authentication_classes = (JWTAuthentication,)
    pagination_class = StandardResultsSetPagination
    filter_backends = [
        DjangoFilterBackend,

store/templates/store/_mini-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    {% block title %}
        <!-- Title of page gos here -->

    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'store/asset/fonts/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/css/now-ui-kit.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/css/plugins/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/css/plugins/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/css/main.css' %}">

    {% block css %}
        <!-- Specific CSS files of each page go here -->

    {% endblock %}
</head>
<body class="index-page sidebar-collapse">
    <div class="wrapper default">


        {% block main %}
            <!-- The main part of each page goes here -->
        {% endblock %}

        <footer class="mini-footer">
            <nav>
                <div class="container">
                    <ul class="menu">
                        <li>
                            <a href="#">درباره کالانگار</a>
                        </li>
                        <li>
                            <a href="#">فرصت‌های شغلی</a>
                        </li>
                        <li>
                            <a href="#">تماس با ما</a>
                        </li>
                        <li>
                            <a href="#">همکاری با سازمان‌ها</a>
                        </li>

                    </ul>
                </div>
            </nav>
            <div class="copyright-bar">
                <div class="container">
                    <p>
                        استفاده از مطالب فروشگاه اینترنتی کالانگار فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                        کلیه حقوق این سایت متعلق
                        به شرکت نوآوران فن آوازه (فروشگاه آنلاین کالانگار) می‌باشد.
                    </p>
                </div>
            </div>
        </footer>
    </div>


    <!--   Core JS Files   -->
    <script type="text/javascript" src="{% static 'store/vendor/js/core/jquery.3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'store/vendor/js/core/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'store/vendor/js/core/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'store/vendor/js/core/axios.min.js' %}"></script>

    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/bootstrap-switch.js' %}"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/nouislider.min.js' %}"></script>

    <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/bootstrap-datepicker.js' %}"></script>

    <!-- Share Library etc -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/jquery.sharrre.js' %}"></script>

    <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
    <script type="text/javascript" src="{% static 'store/vendor/js/now-ui-kit.js' %}"></script>

    <!--  CountDown -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/countdown.min.js' %}"></script>

    <!--  Plugin for Sliders -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/owl.carousel.min.js' %}"></script>

    <!--  Jquery easing -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/jquery.easing.1.3.min.js' %}"></script>

    <!--  LocalSearch -->
    <script type="text/javascript" src="{% static 'store/vendor/js/plugins/JsLocalSearch.js' %}"></script>

    <!-- Main Js -->
    <script type="text/javascript" src="{% static 'store/vendor/js/main.js' %}"></script>


    {% block js %}
        <!-- Specific JS files of each page go here -->

    {% endblock %}
</body>
</html>

store/templates/store/cart.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title id="page-title">سبد خرید</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'store/css/cart.css' %}">
{% endblock %}

{% block main %}
    <main class="cart-page default">
            <div class="container">
                <div class="row">
                    <div class="cart-page-content col-xl-9 col-lg-8 col-md-12 order-1">
                        <div class="cart-page-title">
                            <h1>سبد خرید</h1>
                        </div>
                        <div class="table-responsive checkout-content default">
                            <table class="table">
                                <tbody id="cart-items-tbody">

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <aside class="cart-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-2">
                        <div class="checkout-aside">
                            <div class="checkout-summary">
                                <div class="checkout-summary-main">
                                    <ul class="checkout-summary-summary">
                                        <li id="cart-price-details">

                                        </li>
                                        <li>
                                            <span>هزینه ارسال</span>
                                            <span>وابسته به آدرس<span class="wiki wiki-holder"><span
                                                        class="wiki-sign"></span>
                                                    <div class="wiki-container js-dk-wiki is-right">
                                                        <div class="wiki-arrow"></div>
                                                        <p class="wiki-text">
                                                            هزینه ارسال مرسولات می‌تواند وابسته به شهر و آدرس گیرنده
                                                            متفاوت باشد. در
                                                            صورتی که هر
                                                            یک از مرسولات حداقل ارزشی برابر با ۱۰۰هزار تومان داشته باشد،
                                                            آن مرسوله
                                                            بصورت رایگان
                                                            ارسال می‌شود.<br>
                                                            "حداقل ارزش هر مرسوله برای ارسال رایگان، می تواند متغیر
                                                            باشد."
                                                        </p>
                                                    </div>
                                                </span></span>
                                        </li>
                                    </ul>
                                    <div class="checkout-summary-devider">
                                        <div></div>
                                    </div>
                                    <div class="checkout-summary-content">
                                        <div class="checkout-summary-price-title">مبلغ قابل پرداخت:</div>
                                        <div class="checkout-summary-price-value">
                                            <span class="checkout-summary-price-value-amount"></span>تومان
                                        </div>
                                        <a href="#" class="selenium-next-step-shipping">
                                            <div class="parent-btn">
                                                <button class="dk-btn dk-btn-info">
                                                    ادامه ثبت سفارش
                                                    <i class="now-ui-icons shopping_basket"></i>
                                                </button>
                                            </div>
                                        </a>
                                        <div>
                                            <span>
                                                کالاهای موجود در سبد شما ثبت و رزرو نشده‌اند، برای ثبت سفارش مراحل بعدی
                                                را تکمیل
                                                کنید.
                                            </span>
                                            <span class="wiki wiki-holder"><span class="wiki-sign"></span>
                                                <div class="wiki-container is-right">
                                                    <div class="wiki-arrow"></div>
                                                    <p class="wiki-text">
                                                        محصولات موجود در سبد خرید شما تنها در صورت ثبت و پرداخت سفارش
                                                        برای شما رزرو
                                                        می‌شوند. در
                                                        صورت عدم ثبت سفارش، کالانگار هیچگونه مسئولیتی در قبال تغییر
                                                        قیمت یا موجودی
                                                        این کالاها
                                                        ندارد.
                                                    </p>
                                                </div>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="checkout-feature-aside">
                                <ul>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-guarantee">
                                        هفت روز
                                        ضمانت تعویض
                                    </li>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-cash">
                                        پرداخت در محل با
                                        کارت بانکی
                                    </li>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-express">
                                        تحویل اکسپرس
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </main>

{% endblock %}

{% block js %}
     <!--  Plugin ez-plus -->

    <script type="text/javascript" src="{% static 'store/js/cart.js' %}"></script>
{% endblock %}

store/templates/store/category-products.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title id="page-title"></title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'store/css/category-products.css' %}">
{% endblock %}

{% block main %}
    <main class="default">
        <div class="category-products-container container">
            <div class="sub-cat-title">
                دسته بندی های
                <strong style="color: #0fafdd" id="cat-name"></strong>
            </div>
            <div class="mx-0" id="this-cat-subs-container">

            </div>
            <div id="last-cat-products-container">
                <div class="row">
                    <div class="col-12">
                        <div class="widget widget-product card">
                            <header class="card-header">
                                <h3 class="card-title">
                                    <span id="category-name"></span>
                                </h3>
                            </header>
                            <div class="product-carousel owl-carousel owl-theme" id="category-last-products">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script src="{% static 'store/js/category-products.js' %}"></script>
{% endblock %}

store/templates/store/error-404.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title>صفحه مورد نظر پیدا نشد</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}
    <main class="page-404">
        <div class="container text-center">
            <div class="page-404-title">
                <h1>صفحه‌ای که دنبال آن بودید پیدا نشد!</h1>
            </div>
            <div class="page-404-actions">
                <a href="{% url 'store:home' %}" class="page-404-action page-404-action--primary">صفحه اصلی</a>
            </div>
            <div class="page-404-image">
                <img src="../../static/store/asset/image/homePage/404.png">
            </div>
        </div>
    </main>
{% endblock %}