kilometer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import RedirectView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),

    # store api urls
    url(r'^api/store/', include(('store.api.urls', 'api-store'), namespace='api-store')),

    # website urls
    url(r'^', include('store.urls')),

    # manager panel urls
    url(r'^management-panel/', include('manager_panel.urls')),

    # user panel urls
    url(r'^profile/', include('user_panel.urls')),

    # user panel api urls
    url(r'^api/user/', include('user_panel.api.urls')),

    # user manager api urls
    url(r'^api/manager/', include('manager_panel.api.urls')),

    url(r'^api-auth/', include('rest_framework.urls')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager_panel/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'api-manager'


router = DefaultRouter()
router.register('slide-show', views.ManagerSlideShowViewSet)
router.register('category', views.ManagerCategoryViewSet)
router.register('sub-category', views.ManagerSubCategoryViewSet)
router.register('sub-sub-category', views.ManagerSubSubCategoryViewSet)
router.register('brand', views.ManagerBrandViewSet)
router.register('ware', views.ManagerWareViewSet)
router.register('ware-picture', views.ManagerWarePictureViewSet)
router.register('price', views.ManagerPriceViewSet)
router.register('special-offer', views.ManagerSpecialOfferViewSet)
router.register('instant-offer', views.ManagerInstantOfferViewSet)
router.register('sale', views.ManagerSaleViewSet)
router.register('color', views.ManagerColorViewSet)
router.register('product', views.ManagerProductViewSet)
router.register('user', views.ManagerUserViewSet)
router.register('report', views.ManagerReportViewSet)
router.register('tag', views.ManagerTagViewSet)

urlpatterns = [
    path('info/', views.ManagerInfoView.as_view(), name='Info'),
    path('', include(router.urls)),
]

manager_panel/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

app_name = 'manager_panel'

urlpatterns = [
    url(r'^$', views.management_panel, name='managementPanel'),
    url(r'^personal-info/$', views.personal_info, name='personalInfo'),
    url(r'^additional-info/$', views.additional_info, name='additionalInfo'),
    url(r'^all-orders/$', views.all_orders, name='allOrders'),
    url(r'^returned-orders/$', views.returned_orders, name='returnedOrders'),
    url(r'^favorite-products/$', views.favorite_products, name='favoriteProducts'),
    url(r'^add-product-category/$', views.add_product_category, name='addProductCategory'),
    url(r'^add-brand/$', views.add_brand, name='addBrand'),
    url(r'^add-color/$', views.add_color, name='addColor'),
    url(r'^add-tag/$', views.add_tag, name='addTag'),
    url(r'^add-slideshow/$', views.add_slideshow, name='addSlideshow'),
    url(r'^products-list/$', views.products_list, name='productsList'),
    url(r'^add-product/$', views.add_product, name='addProduct'),
    url(r'^users-list/$', views.users_list, name='usersList'),
]

store/urls.py
from django.conf.urls import url, re_path
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.generic.base import RedirectView


app_name = 'store'

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^error-404/$', views.error_404, name='error404'),
    re_path(r'product/(?P<pk>\w+)', views.single_product, name='singleProduct'),
    path('global-search/products/', views.global_search, name='globalSearch'),
    path('sub-category/<int:pk>/', views.sub_category_products, name='subCategory'),
    path('category/<str:slug>/', views.category_products, name='Category'),
    path('cart/', views.cart, name='cart'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('scrape-products/', views.scrape_products, name='scrape-product'),
    # re_path(
    #     r'product/(?P<pk>\w+)/(?P<slug>[-\w]+)/',
    #     TemplateView.as_view(template_name="store/single-product.html"),
    #     name='singleProduct'),
]

manager_panel/api/views.py
from django.utils.text import slugify
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import viewsets, generics, mixins
from . import permissions
from rest_framework_simplejwt.authentication import JWTAuthentication
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from rest_framework.pagination import PageNumberPagination
from rest_framework import status
from . import serializers
from store import models
from django.contrib.auth import get_user_model


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 20
    page_size_query_param = 'page_size'
    max_page_size = 100


class ManagerInfoView(generics.RetrieveUpdateAPIView):
    """Show detailed of manager user"""
    serializer_class = serializers.UserSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    queryset = get_user_model().objects.all()

    def get_object(self):
        """Retrieve anr return authenticated user"""
        return self.request.user


class ManagerUserViewSet(viewsets.GenericViewSet,
                         mixins.ListModelMixin,
                         mixins.RetrieveModelMixin):
    """user for manager"""

    serializer_class = serializers.UserSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = get_user_model().objects.all()

    def get_queryset(self):
        """Filter user that doesn't show admin or staff"""
        return self.queryset.filter(
            is_superuser=False, is_staff=False
        ).exclude(groups__name='Manager')


class ManagerSlideShowViewSet(viewsets.ModelViewSet):
    """Manage slideshow in database"""

    serializer_class = serializers.SlideShowSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.SlideShow.objects.all()


class ManagerInstantOfferViewSet(viewsets.ModelViewSet):
    """Manage instant offers in database"""

    serializer_class = serializers.SlideShowSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.InstantOffer.objects.all()


class ManagerCategoryViewSet(viewsets.ModelViewSet):
    """Manage categories in database"""

    serializer_class = serializers.CategorySerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Category.objects.all()


class ManagerSubCategoryViewSet(viewsets.ModelViewSet):
    """Manage sub category in database"""

    serializer_class = serializers.SubCategorySerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.SubCategory.objects.all()


class ManagerSubSubCategoryViewSet(viewsets.ModelViewSet):
    """Manage sub sub category in database"""

    serializer_class = serializers.SubSubCategorySerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.SubSubCategory.objects.all()


class ManagerBrandViewSet(viewsets.ModelViewSet):
    """Manage brand in database"""

    serializer_class = serializers.BrandSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Brand.objects.all()

    def perform_create(self, serializer):
        serializer.save(slug=slugify(serializer.validated_data['en_name'], allow_unicode=True))

    def perform_update(self, serializer):
        serializer.save(slug=slugify(serializer.validated_data['en_name'], allow_unicode=True))


class ManagerWareViewSet(viewsets.ModelViewSet):
    """Manage ware in database"""

    serializer_class = serializers.WareSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Ware.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter
    ]
    search_fields = ('name',)

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return serializers.WareDetailSerializer
        else:
            return self.serializer_class

    def get_queryset(self):

        # get query params
        brand = self.request.query_params.get('brand')
        sub_category = self.request.query_params.get('sub_category')

        # get queryset
        queryset = self.queryset

        # filter by brand
        if brand:
            brand = brand.split(',')
            queryset = queryset.filter(brand_id__in=brand)

        if sub_category:
            sub_category = sub_category.split(',')
            queryset = queryset.filter(sub_category_id__in=sub_category)

        return queryset

    def perform_create(self, serializer):
        serializer.save(slug=slugify(serializer.validated_data['name'], allow_unicode=True))

    def perform_update(self, serializer):
        serializer.save(slug=slugify(serializer.validated_data['name'], allow_unicode=True))


class ManagerProductViewSet(viewsets.ModelViewSet):
    """Manage ware in database"""

    serializer_class = serializers.ProductSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Product.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter
    ]
    filterset_fields = ['ware__sub_category', 'ware__brand', 'color']
    search_fields = ('ware__name',)

    def perform_create(self, serializer):
        models.Price.objects.create(
            user=self.request.user,
            ware=serializer.validated_data['ware'],
            price=serializer.validated_data['price']
        )
        serializer.save()

    def perform_update(self, serializer):
        if serializer.validated_data['price']:
            print(self.get_object().ware.id)
            last_price = models.Price.objects.filter(ware_id=self.get_object().ware.id).order_by('-created_on')[0]
            if last_price.price != serializer.validated_data['price']:
                models.Price.objects.create(
                    user=self.request.user,
                    ware_id=self.get_object().ware.id,
                    price=serializer.validated_data['price']
                )
        serializer.save()

    def perform_destroy(self, instance):
        products = models.Product.objects.filter(ware=instance.ware).exclude(id=instance.id)
        print(products)
        try:
            temp = models.Product.objects.get(id=products[0].id)
            temp.default = True
            temp.save()
        except IndexError:
            pass
        instance.delete()

    def get_serializer_class(self):
        if self.action == 'list' or self.action == 'retrieve':
            return serializers.ShowProductSerializer
        else:
            return self.serializer_class


class ManagerColorViewSet(viewsets.ModelViewSet):
    """Manage ware in database"""

    serializer_class = serializers.ColorSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Color.objects.all()


class ManagerWarePictureViewSet(viewsets.ModelViewSet):
    """Manage ware picture in database"""

    serializer_class = serializers.WarePictureSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.PictureWare.objects.all()


class ManagerPriceViewSet(viewsets.GenericViewSet,
                          mixins.ListModelMixin,
                          mixins.RetrieveModelMixin):
    """Manage price in database"""

    serializer_class = serializers.PriceSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Price.objects.all()

    def perform_create(self, serializer):
        """Create a new object"""
        serializer.save(user=self.request.user)


class ManagerSpecialOfferViewSet(viewsets.ModelViewSet):
    """Manage special offer in database"""

    serializer_class = serializers.SpecialOfferSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.SpecialOffer.objects.all()


class ManagerSaleViewSet(viewsets.GenericViewSet,
                         mixins.ListModelMixin,
                         mixins.RetrieveModelMixin):
    """Manage sale in database"""

    serializer_class = serializers.SaleSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (permissions.IsManager,)
    pagination_class = StandardResultsSetPagination
    queryset = models.Sale.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter
    ]
    filterset_fields = ['status']
    search_fields = ('ware__name',)

    def get_serializer_class(self):
        if self.action == 'list':
            return self.serializer_class
        else:
            return serializers.SaleDetailSerializer


class ManagerReportViewSet(viewsets.GenericViewSet,

manager_panel/views.py
from django.shortcuts import render


def management_panel(request):
    return render(request, 'manager_panel/management-panel.html', {})


def personal_info(request):
    return render(request, 'manager_panel/personal-info.html')


def additional_info(request):
    return render(request, 'manager_panel/additional-info.html')


def all_orders(request):
    return render(request, 'manager_panel/all-orders.html')


def returned_orders(request):
    return render(request, 'manager_panel/returned-orders.html')


def favorite_products(request):
    return render(request, 'manager_panel/favorite-products.html')


def add_product_category(request):
    return render(request, 'manager_panel/add-product-category.html')


def add_product(request):
    return render(request, 'manager_panel/add-product.html')


def users_list(request):
    return render(request, 'manager_panel/users-list.html')


def products_list(request):
    return render(request, 'manager_panel/products-list.html')


def add_brand(request):
    return render(request, 'manager_panel/add-brand.html')


def add_color(request):
    return render(request, 'manager_panel/add-color.html')


def add_tag(request):
    return render(request, 'manager_panel/add-tag.html')


def add_slideshow(request):
    return render(request, 'manager_panel/add-slideshow.html')

manager_panel/templates/manager_panel/additional-info.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title>حساب کاربری | ویرایش اطلاعات شخصی</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}
    <main class="profile-user-page default">
        <div class="container">
            <div class="row">
                <div class="profile-page col-xl-9 col-lg-8 col-md-12 order-2">
                    <div class="row">
                        <div class="col-12">
                            <div class="col-12">
                                <h1 class="title-tab-content">ویرایش اطلاعات شخصی</h1>
                            </div>
                            <div class="content-section default">
                                <div class="row">
                                    <div class="col-12">
                                        <h1 class="title-tab-content">حساب شخصی</h1>
                                    </div>
                                </div>
                                <div class="form-account">
                                    <div class="row">
                                        <div class="col-sm-12 col-md-6">
                                            <div class="form-account-title">نام و نام خانوادگی</div>
                                            <div class="form-account-row">
                                                <input class="input-field text-right" id="manager-additional-name" type="text" placeholder="نام خود را وارد نمایید">
                                            </div>
                                        </div>
                                        <div class="col-sm-12 col-md-6">
                                            <div class="form-account-title">کد ملی</div>
                                            <div class="form-account-row">
                                                <input class="input-field text-right" id="manager-additional-national-code" type="text" pattern="\d*" maxlength="10" placeholder="کد ملی خود را وارد نمایید">
                                            </div>
                                        </div>
                                        <div class="col-sm-12 col-md-6">
                                            <div class="form-account-title">شماره موبایل</div>
                                            <div class="form-account-row">
                                                <input class="input-field text-right" id="manager-additional-phone-number" type="text" pattern="\d*" maxlength="11" placeholder="شماره موبایل خود را وارد نمایید">
                                            </div>
                                        </div>
                                        <div class="col-sm-12 col-md-6">
                                            <div class="form-account-title">شماره کارت</div>
                                            <div class="form-account-row">
                                                <input class="input-field text-right" id="manager-additional-bank-card-number" type="text" pattern="\d*" maxlength="16" placeholder=" شماره کارت خود را وارد نمایید">
                                            </div>
                                        </div>
                                        <div class="col-sm-12 col-md-6">
                                            <div class="form-account-title">آدرس ایمیل</div>
                                            <div class="form-account-row">
                                                <input class="input-field text-right" id="manager-additional-email" type="email" placeholder=" آدرس ایمیل خود را وارد نمایید">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 d-block" style="color: red" id="errors-box">

                                    </div>
                                    <div class="col-12 text-center">
                                        <button class="btn btn-default btn-lg" onclick="updateManagerInfo()">ذخیره</button>
                                        <a href="{% url 'manager_panel:managementPanel' %}"><button class="btn btn-default btn-lg">انصراف</button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'manager_panel/_management-panel-sidebar.html' %}
            </div>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/additional-info.js' %}"></script>
{% endblock %}

manager_panel/templates/manager_panel/management-panel.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title>پنل مدیریت</title>
{% endblock %}
{% block css %}
    {# CSS files... #}
{% endblock %}


{% block main %}
    <main class="profile-user-page default" id="manager-panel-container" style="display: none">
        <div class="container">
            <div class="row">
                <div class="profile-page col-xl-9 col-lg-8 col-md-12 order-2">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="col-12">
                                <h1 class="title-tab-content">اطلاعات شخصی</h1>
                            </div>
                            <div class="content-section default" style="overflow: hidden">
                                <div class="row">
                                    <div class="col-12">
                                        <p>
                                            <span class="title">نام و نام خانوادگی :</span>
                                            <span id="management-panel-name"></span>
                                        </p>
                                    </div>
                                    <div class="col-12">
                                        <p>
                                            <span class="title">پست الکترونیک :</span>
                                            <span id="management-panel-email"></span>
                                        </p>
                                    </div>
                                    <div class="col-12">
                                        <p>
                                            <span class="title">شماره تلفن همراه:</span>
                                            <span id="management-panel-phone"></span>
                                        </p>
                                    </div>
                                    <div class="col-12">
                                        <p>
                                            <span class="title">کد ملی :</span>
                                            <span id="management-panel-national-code"></span>
                                        </p>
                                    </div>
                                    <div class="col-12">
                                        <p>
                                            <span class="title">شماره کارت :</span>
                                            <span id="management-panel-bank-card-number"></span>
                                        </p>
                                    </div>
                                    <div class="col-12 text-center">
                                        <a href="{% url 'manager_panel:additionalInfo' %}" class="btn-link-border form-account-link">
                                            ویرایش اطلاعات شخصی
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="col-12">
                                <h1 class="title-tab-content">لیست آخرین سفارشات</h1>
                                <div class="content-section default">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="profile-recent-fav-row">
                                            <a href="#" class="profile-recent-fav-col profile-recent-fav-col-thumb">
                                                <img src="{% static 'store/asset/image/homePage/cart/4560621.jpg' %}">
                                            </a>
                                            <div class="profile-recent-fav-col profile-recent-fav-col-title">
                                                <a href="#">
                                                    <h4 class="profile-recent-fav-name">
                                                        گوشی موبایل اپل مدل iPhone XR دو سیم کارت ظرفیت 256 گیگابایت
                                                    </h4>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="profile-recent-fav-row">
                                            <a href="#" class="profile-recent-fav-col profile-recent-fav-col-thumb">
                                                <img src="{% static 'store/asset/image/homePage/cart/3794614.jpg' %}"></a>
                                            <div class="profile-recent-fav-col profile-recent-fav-col-title">
                                                <a href="#">
                                                    <h4 class="profile-recent-fav-name">
                                                        گوشی موبایل اپل مدل iPhone XR دو سیم کارت ظرفیت 256 گیگابایت
                                                    </h4>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 text-center">
                                        <a href="{% url 'manager_panel:allOrders' %}" class="btn-link-border form-account-link">
                                            مشاهده و ویرایش لیست سفارشات
                                        </a>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'manager_panel/_management-panel-sidebar.html' %}
            </div>
        </div>
    </main>
{% endblock %}


{% block js %}
    <!-- JS files... -->
    <script type="text/javascript" src="{% static 'js/_manager-panel.js' %}"></script>
{% endblock %}

manager_panel/templates/manager_panel/personal-info.html
{% extends 'store/_base.html' %}
{% load static %}
{% block title %}
    <title>حساب کاربری | اطلاعات شخصی</title>
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}
    <main class="profile-user-page default">
        <div class="container">
            <div class="row">
                <div class="profile-page col-xl-9 col-lg-8 col-md-12 order-2">
                    <div class="row">
                        <div class="col-12">
                            <div class="col-12">
                                <h1 class="title-tab-content">اطلاعات شخصی</h1>
                            </div>
                            <div class="content-section default">
                                <div class="row">
                                    <div class="col-sm-12 col-md-6">
                                        <p>
                                            <span class="title">نام و نام خانوادگی :</span>
                                            <span id="manager-name"></span>
                                        </p>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <p>
                                            <span class="title">پست الکترونیک :</span>
                                            <span id="manager-email"></span>
                                        </p>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <p>
                                            <span class="title">شماره تلفن همراه:</span>
                                            <span id="manager-phone-number"></span>
                                        </p>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <p>
                                            <span class="title">کد ملی :</span>
                                            <span id="manager-national-code"></span>
                                        </p>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <p>
                                            <span class="title">شماره کارت :</span>
                                            <span id="manager-bank-card-number"></span>
                                        </p>
                                    </div>
                                    <div class="col-12 text-center">
                                        <a href="{% url 'manager_panel:additionalInfo' %}" class="btn-link-border form-account-link">
                                            ویرایش اطلاعات شخصی
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'manager_panel/_management-panel-sidebar.html' %}
            </div>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/personal-info.js' %}"></script>
{% endblock %}